### ISSUE TITLE
Unhandled exception. System.Net.Sockets.SocketException (98): Address already in use

### ISSUE THREAD

**Issue by chaojicpu** [jchristn/SimpleUdp#4]
Unhandled exception. System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.UdpClient..ctor(Int32 port, AddressFamily family)
   at System.Net.Sockets.UdpClient..ctor(Int32 port)
   at SimpleUdp.UdpEndpoint..ctor(String ip, Int32 port)
   at pidemo.Program.Main(String[] args) in E:\Projects\netcoreapi\pidemo\pidemo\Program.cs:line 102
It doesn't seem to work in the arm environment!

**Comment by jchristn** [comment]
Hi @chaojicpu sorry I never received a notification on this!  Did you already have a listener attached to that port?  What port number were you using?  Were you running as a normal user or superuser/admin/root?
